/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_ap1.kasir.client;

import com.mysql.jdbc.PreparedStatement;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rjial
 */
public class PesanMenu extends javax.swing.JFrame {
    private Connection con = ConfigDB.ambil_koneksi();
    private HashMap<String, Menu> daftarMenu = new HashMap<String, Menu>();
    private HashMap<String, Menu> daftarMenuMinuman = new HashMap<String, Menu>();
    private HashMap<String, Menu> daftarMenuSelected = null;
    private String idMenu_selected;
    private Main main;

    /**
     * Creates new form PesanMenu
     */
    public PesanMenu() {
        initComponents();
    }
    
    public void setDaftarMenuSelected(HashMap<String, Menu> daftarMenuSelected) {
        this.daftarMenuSelected = daftarMenuSelected;
    }
    
    public void setMainForm(Main main) {
        this.main = main;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMenuMinuman = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenuMakanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Makanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Minuman");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Menu", "Nama Minuman", "Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblMenuMinuman);

        jPanel4.add(jScrollPane3);

        jPanel2.add(jPanel4, "cardMinuman");

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Menu", "Nama Makanan", "Stok", "Harga"
            }
        ));
        tblMenuMakanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMakananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMenuMakanan);

        jPanel3.add(jScrollPane2);

        jPanel2.add(jPanel3, "cardMakanan");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_ap1/kasir/client/gambar/Frame 11.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_ap1/kasir/client/gambar/MENU.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_ap1/kasir/client/gambar/.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        CardLayout cardL = (CardLayout) jPanel2.getLayout();
        cardL.show(jPanel2, "cardMakanan");
        update_makanan();
        update_minuman();
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardL = (CardLayout) jPanel2.getLayout();
        cardL.show(jPanel2, "cardMakanan");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cardL = (CardLayout) jPanel2.getLayout();
        cardL.show(jPanel2, "cardMinuman");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void tblMenuMakananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMakananMouseClicked
        // TODO add your handling code here:
        int baris = tblMenuMakanan.rowAtPoint(evt.getPoint());
        idMenu_selected = tblMenuMakanan.getValueAt(baris, 0).toString();
    }//GEN-LAST:event_tblMenuMakananMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        List<Menu> listSelectedMakanan = new ArrayList<>();
        listSelectedMakanan.clear();
        daftarMenuSelected = new HashMap<String, Menu>();
//        int[] indexSelectedMenu = tblMenuMakanan.getSelectedRows();
        if (tblMenuMakanan.getSelectedRows().length > 0 || tblMenuMinuman.getSelectedRows().length > 0) {
            for (int index : tblMenuMakanan.getSelectedRows()) {
//            System.out.println(index);
                String id_menuSelected = tblMenuMakanan.getValueAt(index, 0).toString();
                listSelectedMakanan.add(daftarMenu.get(id_menuSelected));
                daftarMenuSelected.put(id_menuSelected, daftarMenu.get(id_menuSelected));
            }
            for (int index : tblMenuMinuman.getSelectedRows()) {
//            System.out.println(index);
                String id_menuSelected = tblMenuMinuman.getValueAt(index, 0).toString();
                listSelectedMakanan.add(daftarMenuMinuman.get(id_menuSelected));
                daftarMenuSelected.put(id_menuSelected, daftarMenuMinuman.get(id_menuSelected));
            }
//        for (int i = 0; i < listSelectedMakanan.size(); i++) {
//            Menu menuSel = listSelectedMakanan.get(i);
//            System.out.println(menuSel.getNamaMenu());
//        }

            Checkout checkout = new Checkout();
            checkout.setListMenuSelected(listSelectedMakanan);
            checkout.setDaftarPilih(daftarMenuSelected);
            checkout.setPsnMenuForm(this);
            checkout.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Harap pilih salah satu menu!", "Drive Thru", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
//        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentAdded

    private void update_makanan() {
        try {
            idMenu_selected = null;
            String sqlmakanan = "SELECT * FROM menu INNER JOIN makanan ON makanan.ID_MENU = menu.ID_MENU";
//            String output = "select * from menu, makanan, minuman";
            PreparedStatement pst = (PreparedStatement) con.prepareStatement(sqlmakanan);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel tb_list_makanan = (DefaultTableModel) tblMenuMakanan.getModel();
            tb_list_makanan.setRowCount(0);
            daftarMenu.clear();

            while (rs.next()) {
                Vector columndata = new Vector();
                for (int i = 1; i < q; i++) {
                   daftarMenu.put(rs.getString("ID_MENU"), new Menu(rs.getString("ID_MENU"), rs.getString("NAMA_MAKANAN"), rs.getInt("STOCK"), rs.getInt("HARGA"), rs.getBinaryStream("GAMBAR_MENU"), 0, 0));
//                    columndata.add(rs.getString("STOCK"));
//                    columndata.add(rs.getString("NAMA_MAKANAN"));
                    columndata.add(rs.getString("ID_MENU"));
                    columndata.add(rs.getString("NAMA_MAKANAN"));
                    columndata.add(rs.getString("STOCK"));
                    columndata.add(rs.getString("HARGA"));
                }
                tb_list_makanan.addRow(columndata);
            }
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void update_minuman() {
        String sqlminuman = "SELECT * FROM menu INNER JOIN minuman ON minuman.ID_MENU = menu.ID_MENU";
//            String output = "select * from menu, makanan, minuman";
        try {
            
            PreparedStatement pst = (PreparedStatement) con.prepareStatement(sqlminuman);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel tb_list_minuman = (DefaultTableModel) tblMenuMinuman.getModel();
            tb_list_minuman.setRowCount(0);
            daftarMenuMinuman.clear();

            while (rs.next()) {
                Vector columndata = new Vector();
                for (int i = 1; i < q; i++) {
                    daftarMenuMinuman.put(rs.getString("ID_MENU"), new Menu(rs.getString("ID_MENU"), rs.getString("NAMA_MINUMAN"), rs.getInt("STOCK"), rs.getInt("HARGA"), rs.getBinaryStream("GAMBAR_MENU"), 1, 0));
//                    columndata.add(rs.getString("STOCK"));
//                    columndata.add(rs.getString("NAMA_MAKANAN"));
                    columndata.add(rs.getString("ID_MENU"));
                    columndata.add(rs.getString("NAMA_MINUMAN"));
                    columndata.add(rs.getString("STOCK"));
                    columndata.add(rs.getString("HARGA"));
                }
                tb_list_minuman.addRow(columndata);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PesanMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMenuMakanan;
    private javax.swing.JTable tblMenuMinuman;
    // End of variables declaration//GEN-END:variables
}
